[package]
name = "crc32fast-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.crc32fast]
path = ".."

[[bin]]
name = "hasher"
path = "fuzz_targets/hasher.rs"
test = false
doc = false
bench = false
